### ISSUE TITLE
Building against a recent nixpkgs fails

### ISSUE THREAD

**Issue by dhess** [typeable/nixpkgs-stackage#12]
From my Hydra jobs for a package that builds against the `nixpkgs-unstable` channel and `nixpkgs` `master`:

```
in job ‘lts-9’:
anonymous function at [1m/nix/store/pl7kpwxc7lnkc7n44k5zbzxgfm46jczr-git-export/pkgs/development/haskell-modules/make-package-set.nix[0m:4:1 called without required argument 'buildHaskellPackages', at [1m/nix/store/pl7kpwxc7lnkc7n44k5zbzxgfm46jczr-git-export/lib/customisation.nix[0m:74:12
```

It appears that the recent cross fixes in `nixpkgs` made the `buildHaskellPackages` argument mandatory. See, e.g.:

https://github.com/NixOS/nixpkgs/blob/6d788e9063a5aaef197fc6cdb31e8d903d8c2218/pkgs/top-level/haskell-packages.nix#L129
https://github.com/NixOS/nixpkgs/blob/6d788e9063a5aaef197fc6cdb31e8d903d8c2218/pkgs/development/haskell-modules/default.nix#L2

Here is the upstream commit:

https://github.com/NixOS/nixpkgs/commit/81553124cf32e9d515da5f1c2f1b07e09886d8cf

**Comment by 4e6** [comment]
The problem with `nixpkgs-unstable` is that it breaks compatibility quite frequently. I tried but wasn't able to develop some stable interface to work with it. So, I dropped `nixpkgs-unstable` support.

The issue is obviously in the new `buildHaskellPackages` attribute that was added to the _master_. Do you have any ideas on how we can satisfy both versions of _nixpkgs_, the current `17.09` release and the `master`?

I just checked the code, and currently, arguments of those functions are defined as a set with a fixed arguments number. So if we add `buildHaskellPackages` attribute it'll break `17.09` release.
I think there is a relaxed definition of the attributes set with the triple dots notation `{ arg1, arg2, ... }` which allow passing extra arguments. But even if we'll update the _nixpkgs_ master, this fix will be available only in the next _nixpkgs_ release.

**Comment by dhess** [comment]
I haven't looked at the `nixpkgs-stackage` code in detail, but is this a case where it would help to pin the version of `nixpkgs` that `nixpkgs-stackage` or `stackage2nix` uses internally? Or is this something that needs to run when the overlay is evaluated and depends on the `nixpkgs` that is passed to the overlay as `super`?

In any case, I didn't necessarily expect that `nixpkgs-stackage` would continuously work with `nixpkgs` master. These Hydra builds I'm doing are more of an "early warning system," which looks like it worked as planed in this case :)

**Comment by 4e6** [comment]
Ok, I see. The core of this repo is an overlay [default.nix](https://github.com/typeable/nixpkgs-stackage/blob/master/default.nix) - a giant function `self: super: {}` overriding `super` nixpkgs.

There is another part - [nixpkgs.nix](https://github.com/typeable/nixpkgs-stackage/blob/master/nixpkgs.nix). It takes the system `<nixpkgs>` and applies the overlay. We can pin _nixpkgs.nix_ to some stable version instead of using the system one. It would allow people to use Stackage packages without caring about the Nixpkgs. Assumed that they also don't care about the version of Nixpkgs that was used to build the Stackage packages.

Will the pinning of the _nixpkgs.nix_ work for you?

**Comment by dhess** [comment]
Personally, I only use the overlay in my projects, by importing `default.nix`. I don't use `nixpkgs.nix`. But that's just me, of course.

**Comment by 4e6** [comment]
I addressed the issue with the pinning of _Nixpkgs_ in #14. It also helped to fix the Travis build.

**Comment by dhess** [comment]
Unfortunately, after updating to `nixpkgs-stackage` `master`, I'm still getting the same issue with the `nixpkgs-stackage` overlay. When importing `nixpkgs-stackage` `default.nix` into my overlays, setting `nixpkgs` to the latest `nixpkgs-unstable` (42b9b8f7c8687cb26e69c3559e0e1346fb0e680f), and trying to evaluate a Haskell package set based on `lts-104` or `lts-921`, here is what I get:

```
 nix-build --no-out-link nix/jobsets/release.nix -I nixpkgs=/nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked --show-trace
error: while evaluating the attribute ‘constituents’ of the derivation ‘lts-10’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/pkgs/stdenv/generic/make-derivation.nix:148:11:
while evaluating ‘g’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/attrsets.nix:266:19, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/attrsets.nix:199:52:
while evaluating the attribute ‘lts10Packages’ at /Users/dhess/git/mellon/nix/jobsets/release.nix:78:5:
while evaluating ‘mapAttrs’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/attrsets.nix:198:17, called from /Users/dhess/git/mellon/nix/jobsets/release.nix:78:21:
while evaluating the attribute ‘lts10Packages’ at /Users/dhess/git/mellon/nix/overlays/haskell-overrides.nix:37:3:
while evaluating ‘withLocalMellon’ at /Users/dhess/git/mellon/nix/overlays/lib.nix:30:39, called from /Users/dhess/git/mellon/nix/overlays/haskell-overrides.nix:38:5:
while evaluating the attribute ‘haskell.packages.stackage.lts-104.extend’ at /nix/store/4jhabs3kvbacn7k0p3alnicnzz0qcfij-e9d81ef93e202ecfc0350aca150e2dc4261938ed.tar.gz-unpacked/stackage/default.nix:205:3:
while evaluating ‘callPackageWith’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/customisation.nix:113:35, called from /nix/store/4jhabs3kvbacn7k0p3alnicnzz0qcfij-e9d81ef93e202ecfc0350aca150e2dc4261938ed.tar.gz-unpacked/stackage/default.nix:205:13:
while evaluating ‘makeOverridable’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/customisation.nix:72:24, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/customisation.nix:117:8:
while evaluating anonymous function at /nix/store/4jhabs3kvbacn7k0p3alnicnzz0qcfij-e9d81ef93e202ecfc0350aca150e2dc4261938ed.tar.gz-unpacked/stackage/lts-10.4/default.nix:2:1, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/customisation.nix:74:12:
while evaluating ‘makeExtensibleWithCustomName’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:75:48, called from /nix/store/4jhabs3kvbacn7k0p3alnicnzz0qcfij-e9d81ef93e202ecfc0350aca150e2dc4261938ed.tar.gz-unpacked/stackage/lts-10.4/default.nix:22:21:
while evaluating ‘fix'’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:25:10, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:76:5:
while evaluating ‘extends’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:44:24, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:25:21:
while evaluating ‘extends’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:44:24, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:44:42:
while evaluating ‘extends’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:44:24, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:44:42:
while evaluating ‘extends’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:44:24, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:44:42:
while evaluating ‘extends’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:44:24, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/fixed-points.nix:44:42:
while evaluating ‘callPackageWith’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/customisation.nix:113:35, called from /nix/store/4jhabs3kvbacn7k0p3alnicnzz0qcfij-e9d81ef93e202ecfc0350aca150e2dc4261938ed.tar.gz-unpacked/stackage/lts-10.4/default.nix:11:21:
while evaluating ‘makeOverridable’ at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/customisation.nix:72:24, called from /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/customisation.nix:117:8:
anonymous function at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/pkgs/development/haskell-modules/make-package-set.nix:4:1 called without required argument ‘buildHaskellPackages’, at /nix/store/p6klq4d9l47hf7f9m2dfq9gqpff00cjx-42b9b8f7c8687cb26e69c3559e0e1346fb0e680f.tar.gz-unpacked/lib/customisation.nix:74:12
```

This is with https://github.com/quixoftic/mellon/tree/b9f8aea9439daa9dc7cfa73d2e6b2a7b64eb9cf3

**Comment by 4e6** [comment]
> I'm still getting the same issue with the nixpkgs-stackage overlay.

`nixpkgs-unstable` can't be supported for now. I opened a PR that adds backward compatibility to _haskell-modules. Until https://github.com/typeable/stackage2nix/issues/50 you can use `nixpkgs.nix` that pins Nixpkgs to _17.09_

> The dependency has just moved to configurationNix

Unfortunately, `configurationNix` is not included in `makePackageSet`

**Comment by dhess** [comment]
I can't use `nixpkgs.nix` easily as an overlay, so I'll just wait for https://github.com/NixOS/nixpkgs/pull/34557 and/or https://github.com/typeable/stackage2nix/issues/50. Thanks for all the fixes!

**Comment by dhess** [comment]
Great! All of my LTS packages now evaluate with `nixpkgs-unstable` and the latest commit here... except for LTS-2 -- it appears that `ghc784` has gone missing. I'll dig around, but it's probably unrelated.

Thanks for all of your effort to make this work with `nixpkgs-unstable`!
